name: "NPM Action"
description: "Install and caching npm"
inputs:
  path-of-folder: 
    description: "path of cache folder"
    required: true
runs:
  using: "composite"
  steps:
     - name: Cache NPM dependencies
       uses: actions/cache@v3
       with:
          path: ${{ inputs.path-of-folder }}
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

     - name: Install Dependencies
         run: npm install
         shell: bash